#!/bin/bash
# script to get keyworkd from last hour in nxfitler
# Felipe Ferreira June 2012
# Update 07/2016

#keywords examples I use:
#check_log_nxfilter 'Socket timeout' 20 50
#check_log_nxfilter 'New login session' 300 800
#check_log_nxfilter ' blocked by' 7000 9000
#check_log_nxfilter ' quota block by' 3000 4000

dia=`date +%d`
mesd=`date +%m`
hora=`date +%H -d  "1 hour ago"`

tday="$mesd-$dia $hora:"
logfile="/opt/nxfilter/log/nxfilter.log"

if [ "$3" == "" ]
then
  echo -e "\n Syntax: $0 <key> <Warning> <Critical> \nes.: $0 'New login session' 300 500 \n The script check keyworkds on the last hour inside $logfile\n"
  exit 3
fi

key=$1
warn=$2
crit=$3

key_clean=$(echo $key|tr -d '[[:space:]]'| tr -cd '[[:alnum:]]._-'||sed "s/[[:alpha:].-]//g")

#check if file exists
if [ ! -f $logfile ]; then
        echo "UNKWON - file $logfile not found, maybe no access yet."
        exit 3
fi

CMD="grep "\"$tday"\" $logfile|grep -c "\"$key"\""
#echo $CMD
R=$(eval $CMD)

if [ -z "$R" ] || [ $R -eq 0 ]; then
 FOUND=0
#Maybe we had a logrotated check last lost
logfile="/opt/nxfilter/log/nxfilter.log.1"
CMD="grep "\"$tday"\" $logfile|grep -c "\"$key"\""
#echo $CMD
R=$(eval $CMD)
fi

MSG="Found $R $key for hour $hora |nxfilter_$key_clean=$R"

if [ $R -ge $crit ]; then
 echo "CRITICAL - $MSG"
 exit 2
elif [ $R -ge $warn ]; then
 echo "WARNING - $MSG"
 exit 1
fi

echo "OK - $MSG"
exit 0
